"use client";
import { FormEvent, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, File, FileText, Search, Share2, Trash2, Upload, X } from "lucide-react";
import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { apiClient } from "@/lib/api-client";

type DocumentItem = { id: string; name: string; fileUrl: string; fileType?: string | null; fileSize?: number | null; folder?: string | null; updatedAt: string; uploader: { firstName: string; lastName: string } };
const folders = ["ALL", "General", "Policies", "Contracts", "Financials", "Templates"];
export default function DocumentsPage() {
  const queryClient = useQueryClient();
  const [search, setSearch] = useState("");
  const [folder, setFolder] = useState("ALL");
  const [showUpload, setShowUpload] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [form, setForm] = useState({ name: "", description: "", folder: "General" });
  const query = useQuery<DocumentItem[]>({ queryKey: ["documents"], queryFn: () => apiClient.get("/documents").then((response) => response.data) });
  const upload = useMutation({
    mutationFn: () => {
      const data = new FormData(); data.append("file", file!); data.append("name", form.name || file!.name); data.append("description", form.description); data.append("folder", form.folder);
      return apiClient.post("/documents", data);
    },
    onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["documents"] }); setFile(null); setForm({ name: "", description: "", folder: "General" }); setShowUpload(false); },
  });
  const remove = useMutation({ mutationFn: (id: string) => apiClient.delete(`/documents/${id}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["documents"] }) });
  const documents = useMemo(() => (query.data ?? []).filter((item) => (folder === "ALL" || item.folder === folder) && (!search.trim() || `${item.name} ${item.uploader.firstName} ${item.uploader.lastName}`.toLowerCase().includes(search.toLowerCase()))), [folder, query.data, search]);
  const formatSize = (bytes?: number | null) => bytes ? bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB` : "—";
  function submit(event: FormEvent) { event.preventDefault(); if (file) upload.mutate(); }
  return <DashboardLayout><div className="space-y-7">
    <section className="rounded-[28px] bg-midnight-navy px-6 py-7 text-white"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs"><FileText className="h-3.5 w-3.5 text-teal-300" />Cloud Document Manager</div><h1 className="text-3xl font-bold">Documents Hub</h1><p className="mt-2 text-sm text-slate-300">Upload, organize, open, share, and delete company documents securely.</p></div><button onClick={() => setShowUpload(true)} className="flex items-center gap-2 rounded-xl bg-teal px-4 py-2.5 font-medium"><Upload className="h-4 w-4" /> Upload New File</button></div></section>
    {showUpload && <form onSubmit={submit} className="rounded-2xl border border-border bg-card p-5"><div className="mb-4 flex justify-between"><h2 className="font-semibold">Upload document</h2><button type="button" onClick={() => setShowUpload(false)}><X className="h-5 w-5" /></button></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">File<input required type="file" accept=".pdf,.jpg,.jpeg,.png,.txt,.csv,.docx,.xlsx" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="mt-1 block w-full rounded-xl border p-2" /></label><label className="text-sm font-medium">Display name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder={file?.name || "Document name"} className="mt-1 h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-medium">Folder<select value={form.folder} onChange={(event) => setForm({ ...form, folder: event.target.value })} className="mt-1 h-11 w-full rounded-xl border px-3">{folders.slice(1).map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-medium">Description<input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="mt-1 h-11 w-full rounded-xl border px-3" /></label></div><p className="mt-2 text-xs text-muted-foreground">PDF, JPG, PNG, TXT, CSV, DOCX or XLSX. Maximum 10 MB.</p>{upload.error && <p className="mt-2 text-sm text-red-600">{upload.error.message}</p>}<div className="mt-4 flex justify-end"><button disabled={!file || upload.isPending} className="rounded-xl bg-primary-indigo px-5 py-2 font-semibold text-white disabled:opacity-50">{upload.isPending ? "Uploading..." : "Upload"}</button></div></form>}
    <div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search files..." className="w-full rounded-xl border bg-card py-2 pl-10 pr-3" /></div><div className="flex gap-2 overflow-auto">{folders.map((item) => <button key={item} onClick={() => setFolder(item)} className={`rounded-xl px-3 py-1.5 text-xs font-semibold ${folder === item ? "bg-teal text-white" : "border"}`}>{item}</button>)}</div></div>
    <div className="overflow-x-auto rounded-2xl border bg-card p-6">{query.isLoading ? <p className="py-10 text-center text-muted-foreground">Loading documents...</p> : query.error ? <p className="text-red-600">{query.error.message}</p> : <table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-muted-foreground"><th className="pb-3">Document</th><th className="pb-3">Folder</th><th className="pb-3">Size</th><th className="pb-3">Author</th><th className="pb-3">Updated</th><th className="pb-3 text-right">Actions</th></tr></thead><tbody>{documents.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="py-3.5"><span className="flex items-center gap-2 font-semibold"><File className="h-4 w-4 text-teal" />{item.name}</span></td><td>{item.folder || "General"}</td><td>{formatSize(item.fileSize)}</td><td>{item.uploader.firstName} {item.uploader.lastName}</td><td>{new Date(item.updatedAt).toLocaleDateString()}</td><td><div className="flex justify-end gap-2"><a href={item.fileUrl} target="_blank" rel="noreferrer" title="Open/download"><Download className="h-4 w-4" /></a><button title="Copy share link" onClick={() => navigator.clipboard.writeText(item.fileUrl)}><Share2 className="h-4 w-4" /></button><button title="Delete" onClick={() => window.confirm("Delete this document?") && remove.mutate(item.id)} className="hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}{documents.length === 0 && <tr><td colSpan={6} className="py-12 text-center text-muted-foreground">No documents found.</td></tr>}</tbody></table>}</div>
  </div></DashboardLayout>;
}
